from app.models.domain import (
    ApplicationRecord,
    ApplicationStage,
    CandidateProfile,
    EmploymentType,
    JobListing,
    WorkModel,
)


candidate = CandidateProfile(
    id="candidate_demo",
    full_name="Marina Costa",
    headline="Product Designer com experiencia em SaaS B2B",
    location="Sao Paulo, SP",
    seniority="pleno",
    target_roles=["Product Designer", "UX Designer", "Product Manager"],
    skills=["ux research", "figma", "design system", "analytics", "saas", "prototipacao"],
    languages=["pt-BR", "en"],
    preferences={"remote_first": True, "salary_min": 8500, "timezone": "America/Sao_Paulo"},
)

jobs = [
    JobListing(
        id="job_001",
        title="Product Designer Pleno",
        company="NuvemLabs",
        location="Remoto Brasil",
        work_model=WorkModel.remote,
        employment_type=EmploymentType.clt,
        seniority="pleno",
        salary_min=9000,
        salary_max=12500,
        source="manual_demo",
        source_url="https://example.com/jobs/product-designer-pleno",
        posted_days_ago=2,
        description="Atuar em squads de produto B2B SaaS, conduzir discovery, prototipos e evoluir design system.",
        requirements=["figma", "ux research", "design system", "saas", "prototipacao"],
        benefits=["Plano de saude", "Remoto", "Auxilio educacao"],
    ),
    JobListing(
        id="job_002",
        title="UX Researcher",
        company="ContaVerde",
        location="Sao Paulo, SP",
        work_model=WorkModel.hybrid,
        employment_type=EmploymentType.clt,
        seniority="senior",
        salary_min=11000,
        salary_max=14500,
        source="manual_demo",
        source_url="https://example.com/jobs/ux-researcher",
        posted_days_ago=5,
        description="Pesquisa com usuarios, entrevistas, analise qualitativa e priorizacao com times de produto.",
        requirements=["ux research", "analytics", "entrevistas", "product discovery"],
        benefits=["Hibrido", "Bonus anual"],
    ),
    JobListing(
        id="job_003",
        title="Product Manager",
        company="HealthSync",
        location="Curitiba, PR",
        work_model=WorkModel.remote,
        employment_type=EmploymentType.pj,
        seniority="pleno",
        salary_min=12000,
        salary_max=17000,
        source="manual_demo",
        source_url="https://example.com/jobs/product-manager",
        posted_days_ago=1,
        description="Definir roadmap, acompanhar metricas e liderar descoberta em produto de saude digital.",
        requirements=["roadmap", "analytics", "discovery", "saas", "stakeholders"],
        benefits=["Remoto", "Horario flexivel"],
    ),
]

applications = [
    ApplicationRecord(
        id="app_001",
        job_id="job_001",
        stage=ApplicationStage.saved,
        company="NuvemLabs",
        title="Product Designer Pleno",
        tags=["92% match", "remoto"],
    ),
    ApplicationRecord(
        id="app_002",
        job_id="job_002",
        stage=ApplicationStage.interviewing,
        company="ContaVerde",
        title="UX Researcher",
        sent_at="2026-05-15",
        tags=["entrevista"],
    ),
]
